name: Elixir CI

on:
  push:
    branches: [ master, poc ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.9.0
        otp-version: 22.2
    - name: Install Dependencies
      run: mix deps.get
    - name: Compile Strictly
      run: mix compile --warnings-as-errors
    - name: Check Formatting
      run: mix format --check-formatted
    - name: Check Coding Standard
      run: mix credo --strict
    - name: Run Tests
      run: mix coveralls
